### PR TITLE
Set `forwrev` to 10 by default

### LINKED ISSUE #18: --forwrev should be non-zero by default
Setting `forwrev` to 0 results in an empty dataframe in [forward_backward_convergence](https://github.com/alchemistry/alchemlyb/blob/0916cba61d141e4da171c6891edb9f65aad51ac1/src/alchemlyb/convergence/convergence.py#L15) which breaks other stuff, making `flamel` unusable unless `--forwrev` != 0 is specified.

### PR DESCRIPTION
**Pull request by hejamu**
Fixes #18 

## Description
Sets the `forwrev` command line flags default to 10 (default of the underlying function) to stop flamel from breaking.

## Todos
  - [ ] Needs tests

### CODE REVIEW

**Comment by xiki-tempula** [comment]
Many thanks for the PR. Do you mind giving an example of a case that flamel fails? It is kind of weird that it cannot do this so I want to see if there is an underlying problem.

**Review by orbeckst — CHANGES_REQUESTED** [review]
@hejamu many thanks for checking out the new version and contributing the patch.

A test that runs flamel with *default* args and checks that we get something sensible would be really good. It should also check that defaults are what we expect them to be so that the test fail when defaults are changed.

Please also add an entry to CHANGES.

**Comment by orbeckst** [comment]
P.S.: Apologies for the long delay in reviewing, alchemlyb just hadn't been on my radar lately. You can always get our attention by pinging @xiki-tempula or @orbeckst .

**Comment by xiki-tempula** [comment]
I see. The default for `forwrev` is None in alchemlyb but is 0 in flamel.
I have settled up such that the convergence analysis will be performed if `forwrev` is not None but I haven't dealt with the case of zero.
I will change the alchemlyb to make it handle forwrev=0 as well.

**Comment by orbeckst** [comment]
Changing defaults in alchemlyb comes with deprecation periods due to semantic versioning, I'd just avoid it as much as possible ;-) — This sounds like something that should be handled at the flamel level.

**Comment by xiki-tempula** [comment]
So if I don't need to do convergence analysis, I will usually do `ABFE(forwrev=None)` and if I want to do convergence analysis, I will do `ABFE(forwrev=10)`, these two ways of using ABFE are all fine. However, if someone does `ABFE(forwrev=0)`, the workflow will crash, which is the case here, so I will need to fix the alchemlyb part.

**Comment by hejamu** [comment]
In my opinion it is both a bug in the workflow (i.e. should not crash with forwrev=0) as well as a testing problem in flamel, because the defaults are never tested. I can write the flamel tests.

**Comment by orbeckst** [comment]
Thanks for the explanations. @xiki-tempula could you please raise an issue in alchemlyb so that this can get properly _fixed_ in the ABFE workflow?

@hejamu , flamel tests for defaults would be very welcome!!

**Comment by orbeckst** [comment]
I'll close the PR as superseded by #20

**Comment by orbeckst** [comment]
@hejamu I added you as a GitHub co-author to the merged PR #20 to recognize the work you started in this PR.

**Pull request closed without merging**
