### PR TITLE
Convert flamel to a simple CLI

### PR DESCRIPTION
**Pull request by xiki-tempula**
Given that alchemlyb has reached 1.0. I have also formated the flamel to be a simple CLI interface.
This PR allows flamel to use the alchemlyb.workflow.ABFE as backend and allow this kind of usage.
`flamel -a GROMACS -d {in_path} -f 10 -g -i 50 -j result.csv -m TI,BAR,MBAR -n dE -o {out} -p dhdl -q xvg.bz2 -r 3 -s 50 -t 298 -v -w`

I have refactored the project to make it adopt the molssi cookie-cutter format. I have also added the tests.

### CODE REVIEW

**Comment by orbeckst** [comment]
I am ok with your rewrite. But I will quickly make a historical 0.1.0 release with the original main branch, then merge PR #1 and make a historical 0.2.0, just so that the code remains in the history.

**Review by orbeckst — APPROVED** [review]
The rewrite is in line with discussion #12 .

I added CHANGES and AUTHORS and added it to the branch.

**Comment by xiki-tempula** [comment]
@orbeckst Many thanks for merging this PR. I wonder what is https://github.com/alchemistry/flamel/blob/master/output/pickle.py? I think the file might be introduced by #1 and is no longer needed now.

**Comment by orbeckst** [comment]
oops... I overlooked it in the merge, I'll do a clean-up

**Comment by orbeckst** [comment]
While checking things: Did you use versioneer in the template? I don't see any versioneer files or how is versioning handled? For local test I get
```
(alchemlyb39) flamel oliver$ pytest
============================================================ test session starts ============================================================
platform darwin -- Python 3.9.13, pytest-7.2.0, pluggy-1.0.0
rootdir: ~/flamel
collected 0 items / 1 error

================================================================== ERRORS ===================================================================
_______________________________________________ ERROR collecting flamel/tests/test_flamel.py ________________________________________________
ImportError while importing test module '~/flamel/flamel/tests/test_flamel.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/Users/oliver/anaconda3/envs/alchemlyb39/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
flamel/__init__.py:7: in <module>
    from ._version import __version__
E   ModuleNotFoundError: No module named 'flamel._version'
========================================================== short test summary info ==========================================================
ERROR flamel/tests/test_flamel.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
============================================================= 1 error in 22.17s =============================================================
```

**Comment by xiki-tempula** [comment]
I expect the versioning to be handled by `Versioningit` but this does look weird.

**Comment by xiki-tempula** [comment]
Locally it works for me

**Comment by orbeckst** [comment]
Do I need to install something?

**Comment by xiki-tempula** [comment]
@orbeckst So I think you will need to do `pip install -e .` as the `Versioningit` is set in `pyproject.toml`, which is configured when installing the package.

**Comment by orbeckst** [comment]
Thanks, learning how to live without setup.py and other old-school tools ;-)

**Pull request merged**
